
const C=window.RIZU_CONTENT,R=window.RIZU,s=R.get(),st=R.streak(),ss=R.srsStats();
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
document.querySelector("#dashStreak").textContent=st.current;
document.querySelector("#dashStats").innerHTML=[["Panduan",`${s.guideDone.length}/57`],["Lesson",`${C.curriculum.filter(x=>s.completed.includes(x.id)).length}/${C.curriculum.length}`],["SRS Due",ss.due],["Study Days",st.days],["Best Streak",`${st.best} hari`],["Reading",`${s.readingDone.length}/${C.reading.length}`],["Bookmarks",s.bookmarks.length],["Notes",Object.keys(s.notes).length],["Mock",s.mockHistory.length]].map(x=>`<div class="dash-stat"><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join("");
const heat=document.querySelector("#heatmap");
for(let n=89;n>=0;n--){const d=new Date();d.setDate(d.getDate()-n);const k=R.today(d),a=s.activity[k],events=(a?.events||0)+(a?.minutes||0)/5,l=events===0?0:events<2?1:events<4?2:events<7?3:4;heat.insertAdjacentHTML("beforeend",`<span class="heatday" data-l="${l}" title="${k}: ${a?.events||0} events, ${a?.minutes||0} min"></span>`)}
document.querySelector("#levelBars").innerHTML=C.levels.map(l=>{const p=R.lessonProgress(l);return `<div class="bar-row"><b>${l}</b><div class="bar-track"><span style="width:${p.pct}%"></span></div><span>${p.done}/${p.total}</span></div>`}).join("");
function href(b){if(b.kind==="guide")return `guide.html?id=${encodeURIComponent(b.id)}`;if(b.kind==="atlas-kanji")return `kanji-detail.html?char=${encodeURIComponent(b.id)}`;if(["ono","loan","proverb"].includes(b.kind))return ({ono:"onomatopoeia",loan:"loanwords",proverb:"proverbs"}[b.kind])+`.html?q=${encodeURIComponent(b.label)}`;if(b.kind==="lesson")return`learn.html?id=${encodeURIComponent(b.id)}`;if(b.kind==="reading")return`reader.html?id=${encodeURIComponent(b.id)}`;if(b.kind==="vocab")return`vocabulary.html?level=${encodeURIComponent(b.meta?.level||"N5")}`;if(b.kind==="kanji")return`kanji.html?level=${encodeURIComponent(b.meta?.level||"N5")}`;if(b.kind==="shadowing")return`shadowing.html?id=${encodeURIComponent(b.id)}&level=${encodeURIComponent(b.meta?.level||"N5")}`;return"#"}
document.querySelector("#bookmarkGrid").innerHTML=s.bookmarks.length?s.bookmarks.map(b=>`<a class="bookmark-item" href="${href(b)}"><small>${esc(b.kind.toUpperCase())} · ${esc(b.meta?.level||"")}</small><b>${esc(b.label)}</b><span>${esc(b.meta?.meaning||b.meta?.reading||"")}</span></a>`).join(""):`<div class="notice">Belum ada bookmark.</div>`;
document.querySelector("#notesList").innerHTML=Object.entries(s.notes).length?Object.entries(s.notes).map(([id,n])=>{const l=C.curriculum.find(x=>x.id===id);return`<a class="note-item" href="${id.startsWith("tutorial-")||id.startsWith("keigo-")?"guide":"learn"}.html?id=${encodeURIComponent(id)}"><b>${esc(l?`${l.level} · ${l.title}`:id)}</b><p>${esc(n)}</p></a>`}).join(""):`<div class="notice">Belum ada lesson note.</div>`;
document.querySelector("#mockHistory").innerHTML=s.mockHistory.length?s.mockHistory.map(x=>`<div class="bookmark-item"><small>${esc(x.level)} · ${esc(x.mode.toUpperCase())} · ${new Date(x.at).toLocaleDateString("id-ID")}</small><b>${x.pct}% · diagnostic ${esc(x.sim)}/180</b><span>${esc(x.total)} soal · ${esc(x.durationMin)} menit</span></div>`).join(""):`<div class="notice">Belum ada hasil mock.</div>`;
document.querySelector("#exportData").onclick=R.exportData;
document.querySelector("#importData").onchange=async e=>{try{if(!e.target.files[0])return;if(!confirm("Import akan mengganti progres aktif. Export dahulu jika ingin menyimpan kondisi sekarang. Lanjutkan?")){e.target.value="";return}await R.importData(e.target.files[0]);document.querySelector("#backupStatus").textContent="Import berhasil. Memuat ulang…";setTimeout(()=>location.reload(),500)}catch(err){document.querySelector("#backupStatus").textContent=err.message}};
document.querySelector("#resetData").onclick=()=>{if(confirm("Hapus seluruh progress, SRS, notes, bookmark dan history di browser ini?")){R.resetData();location.reload()}};

document.querySelector('#levelDetails').innerHTML=C.levels.map(l=>{const cards=Object.values(s.srs).filter(x=>x.card.level===l),read=C.reading.filter(x=>x.level===l),listen=C.shadowing.filter(x=>x.level===l),history=s.mockHistory.filter(x=>x.level===l);return '<article><h3>'+l+'</h3><p>Reading '+read.filter(x=>s.readingDone.includes(x.id)).length+'/'+read.length+' · Listening '+listen.filter(x=>s.listeningDone.includes(x.id)).length+'/'+listen.length+'</p><p>SRS '+cards.length+' kartu · '+cards.filter(x=>x.due<=Date.now()).length+' due</p><p>Quiz terbaik: '+(s.quizBest[l]===undefined?'Belum ada':esc(s.quizBest[l])+'%')+'</p><p>Mock: '+history.length+' sesi'+(history.length?' · terakhir '+esc(history[0].pct)+'%':'')+'</p><a class="btn outline" href="learn.html?level='+l+'">Lanjut '+l+'</a></article>'}).join('');
