const C=window.RIZU_CONTENT,R=window.RIZU,O=window.OpenJLPT,E=window.RIZU_EXAM;
let level=R.level(),mode='quick',exam=null,timerId=null,advanceLocked=false;
const root=document.querySelector('#mockRoot'),esc=R.escape;
function setup(){
 clearInterval(timerId);exam=null;const t=C.officialExam2026[level],total=(t.combined||t.vocab+t.grammarReading)+t.listening;
 root.className='mock-setup';root.innerHTML=`<div class="mock-box"><span class="kicker">MOCK JLPT · LATIHAN</span><h2>Pilih level & mode</h2><div class="mock-options">${C.levels.map(l=>`<button class="mock-choice ${level===l?'active':''}" data-l="${l}"><b>${l}</b><span>${C.openjlptCounts.vocab[l]} vocabulary · ${C.openjlptCounts.kanji[l]} kanji</span></button>`).join('')}</div><div class="mock-options"><button class="mock-choice ${mode==='quick'?'active':''}" data-m="quick"><b>Quick Mock</b><span>15 soal · 15 menit</span></button><button class="mock-choice ${mode==='full'?'active':''}" data-m="full"><b>Full Timer Mode</b><span>53 soal latihan · ${total} menit</span></button></div><div class="notice">${t.combined?`Pengetahuan bahasa & reading: ${t.combined} menit dalam satu sesi.`:`Vocabulary: ${t.vocab} menit · Grammar & Reading: ${t.grammarReading} menit.`} Listening: ${t.listening} menit. Komposisi soal latihan bukan salinan atau padanan lengkap ujian resmi. Audio memakai TTS perangkat.</div><p>Pilih jawaban lalu tekan Berikutnya. Sesi yang waktunya habis akan dikunci; jawaban kosong dihitung salah.</p><button class="btn red" id="startMock">Mulai ${level}</button></div>`;
 root.querySelectorAll('[data-l]').forEach(b=>b.onclick=()=>{level=b.dataset.l;R.setLevel(level);setup()});root.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>{mode=b.dataset.m;setup()});root.querySelector('#startMock').onclick=start;
}
async function start(){root.innerHTML='<div class="mock-box"><h2>Menyiapkan soal…</h2></div>';try{let vocab;try{vocab=(await O.load('vocab',level)).data}catch{vocab=C.fallbackVocab.filter(x=>x.level===level)}exam=E.session(C,level,mode,E.build(C,level,mode,vocab));renderExam()}catch(e){root.innerHTML=`<div class="study-error">${esc(e.message)} <button id="backSetup">Kembali</button></div>`;root.querySelector('#backSetup').onclick=setup}}
function stopAudio(){if('speechSynthesis'in window)speechSynthesis.cancel()}
function advance(timeout=false){if(advanceLocked||!exam||exam.finished)return;advanceLocked=true;clearInterval(timerId);stopAudio();E.advance(C,exam,Date.now(),timeout);renderExam();advanceLocked=false}
function tick(){if(!exam||exam.finished)return;const left=Math.max(0,Math.ceil((exam.deadline-Date.now())/1000)),el=root.querySelector('#timer');if(el)el.textContent=`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`;if(left<=0)advance(true)}
function renderExam(){clearInterval(timerId);if(exam.finished)return finish();const q=exam.questions[exam.i];root.className='mock-exam';root.innerHTML=`<div class="exam-head"><div><b>${level} · ${esc(q.section)}</b><div class="data-status">${esc(q.skill)} · Soal ${exam.i+1}/${exam.questions.length}</div></div><div class="timer" id="timer" role="timer">--:--</div></div><div class="exam-q">${q.audio?'<button class="btn red" id="listenQ">▶ Putar audio</button><p id="audioError" role="status"></p>':''}${q.passage?`<div class="reading-passage" lang="ja">${esc(q.passage)}</div>`:''}<h2>${esc(q.q)}</h2><div class="exam-options">${q.choices.map((c,i)=>`<button data-a="${i}" aria-pressed="false">${String.fromCharCode(65+i)}. ${esc(c)}</button>`).join('')}</div><div class="lesson-tools"><button class="btn dark" id="nextExam">Lewati / Berikutnya →</button></div></div>`;
 root.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{if(Date.now()>=exam.deadline){advance(true);return}exam.answers[exam.i]=+b.dataset.a;root.querySelectorAll('[data-a]').forEach(z=>{z.classList.toggle('active',z===b);z.setAttribute('aria-pressed',String(z===b))});root.querySelector('#nextExam').textContent='Simpan & Berikutnya →'});
 root.querySelector('#nextExam').onclick=()=>advance(Date.now()>=exam.deadline);
 if(q.audio)root.querySelector('#listenQ').onclick=()=>R.speak(q.audio,level==='N1'?1:level==='N2'?.95:.86,m=>root.querySelector('#audioError').textContent=m);
 tick();if(!exam.finished)timerId=setInterval(tick,500);
}
function finish(){clearInterval(timerId);stopAudio();if(!exam.saved){exam.result=E.result(exam);R.mockResult(exam.result);exam.saved=true}const result=exam.result,pass=C.officialExam2026[level].pass;root.className='mock-exam';root.innerHTML=`<div class="mock-result"><span class="kicker">HASIL DIAGNOSTIK</span><div class="result-score">${result.pct}%</div><h2>${result.total} soal · pemetaan sederhana ${result.sim}/180</h2><p class="mock-warning">Ini persentase jawaban benar, bukan scaled score atau prediksi kelulusan JLPT. Acuan resmi ${level}: total ${pass}/180; ${['N5','N4'].includes(level)?'minimal 38/120 pada pengetahuan bahasa & reading dan 19/60 pada listening':'minimal 19/60 pada masing-masing tiga bagian penilaian'}. Jumlah soal dan audio TTS latihan berbeda dari ujian resmi.</p><div class="result-sections">${Object.entries(result.sections).map(([name,v])=>`<div><strong>${Math.round(v.ok/v.total*100)}%</strong><span>${esc(name)} · ${v.ok}/${v.total}</span></div>`).join('')}</div><div class="hero-actions"><button class="btn red" id="retryMock">Ulang mock</button><a class="btn dark" href="dashboard.html">Statistik</a></div></div><section class="lesson-section"><h2>Tinjau jawaban</h2>${exam.questions.map((q,i)=>`<details><summary>${i+1}. ${exam.answers[i]===q.answer?'✓':'✗'} ${esc(q.skill)} — ${esc(q.q)}</summary>${q.audio?`<p lang="ja">Transkrip: ${esc(q.audio)}</p>`:''}<p>Jawabanmu: ${exam.answers[i]===null?'Tidak dijawab':esc(q.choices[exam.answers[i]])}</p><p>Jawaban tepat: ${esc(q.choices[q.answer])}</p><p>${esc(q.explain||'')}</p></details>`).join('')}</section>`;root.querySelector('#retryMock').onclick=setup}
window.addEventListener('beforeunload',e=>{if(exam&&!exam.finished){e.preventDefault();e.returnValue=''}});setup();
